### ISSUE TITLE
Solve-a-problem exercise

### ISSUE THREAD

**Issue by cjlortie** [NCEAS/arctic-data-training#1]
On day#2, can tracking data provenance be reduced a bit in time to explore the solve-a-problem model with ADC sample datasets? Either in (deposit) or out (download). The out model is download a dataset, see if it is easy/viable to parse meta-data, then do one analysis/data viz with someone else's data. Great exercise and good practice using repo.

Alt - way to add into agenda, block 1hr to being process at 4pm on Monday, then revisit again on Tuesday at 4pm again to provide gestation and exploration time.

**Comment by mbjones** [comment]
Agenda for the first arctic training was finalized and then executed.  Closing this issue now.
