### ISSUE TITLE
create programming metadata section

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/arctic-data-training#17]
This section should cover

- how to create metadata using `EML`
- how to publish a data package using `datapack`

a draft of the chapter (not numbered) is in the `2019-10-training` branch. awaiting review from @mbjones

**Comment by mbjones** [comment]
I reviewed it. Pasted these comments in Slack, but here as well for the record:

Generally looks good.  I fixed a couple of issues that prevented it from working for me (like param names for the D1Client constructor). And I made a few edits to language.  Overall it looks good but is still fairly complicated. Also, the provenance use case isn’t very compelling — the example I used before had in input -> script -> output, which I think is lacking here.  And its not really explained very much. I guess I would be inclined to include this, but it would be good if we could discuss how to make it more approachable. See my changes in the branch in sha 49bf0164.
