### ISSUE TITLE
Topics

### ISSUE THREAD

**Issue by cjlortie** [NCEAS/arctic-data-training#2]
The training is very focussed on data, DMPs, and repo. Is there room within offering to mention/explore how this effort aligns with reproducible and open science for the Arctic Research Community specifically? Be really nice to see that in there, even briefly.

**Comment by mbjones** [comment]
This first arctic training is complete.  Reconsider curriculum along these lines for the next training. The SASAP training was focused around reproducible workflows and worked very well.
