### ISSUE TITLE
reorganization of the repo

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-training#3]
# Question:
How might the Arctic Data Center outreach and training team structure and organize its training materials for maximum value to both the training team and its users?

# Overview:
This document outlines proposed changes to the arctic-data-training repository in order to establish 1.) a central location for all training components that 2.) enables modular use of existing training materials, 3.) provides exact record of training events, 4.) that is easy to use for both ADC team providing training and ADC users participating in training. 
This approach is modeled after the Mapbox workshops github repo (https://github.com/mapbox/workshops) which serves as both living record & step-by-step training guide for Mapbox developers giving trainings. I was introduced to their approach at Open Street Maps 2017 State of the Map US. See the Mapbox SoTM workshop training page here as an example of a direction I think ADC training could go: https://github.com/mapbox/workshops/tree/sotm2017-osmcha/SoTM-2017
 
## Proposed organization:
Below are proposed changes to the /materials section and a proposal to create an /events folder. NB: This plan hinges on the idea that the ADC team finds a github page in markdown an acceptable format for serving training content. Currently the training repo is geared towards internal users only. The full team should discuss this to make sure all are open to this idea, or the proposed changes below should be adjusted to the team’s consensus on appropriate content serving platforms. 

## NCEAS/arctic-data-training/materials
This section should be organized by training “module”. All training materials should be stored in a folder pertaining to the appropriate training module. This means that each materials folder corresponds to a training topic, which includes the following training materials:
- Presentation slide deck
- Sample data sets
- Any instruction / how-to guide
- Any other content used in the training

Goal: 
For ADC team: 
- Easy, modular use & reuse of existing training materials 
- Training materials are linkable in training agenda
- Serves as a record and a central location for all training materials
For users: 
- Easy to peruse content during, or after the training
- Ability to perform some informal self-guided training

### Example of Materials Folder organization:
- R training: would house arctic-data-center-training.rproj, Bulk-data-upload, Data packaging, Hierarchical packaging, Query and download
- NSF data policies
- ADC: would house [Overview](https://github.com/NCEAS/arctic-data-training/blob/gh-pages/materials/session-1-arctica-overview-mjones-v03.pdf), How to connect with ADC, ADC Submission Best practices
- Data management plan training: would house ArcticDataCenter_DMP.pdf
- Metadata: would house [What is metadata](https://github.com/NCEAS/arctic-data-training/blob/gh-pages/materials/session-3_authoring-quality-metadata_mecum.pdf), Preparing complete metadata
- Data management best practices: including Versioning your dataset, Open Source formats
Identifiers
- Data Discovery and Re-use
- Data provenance

## NCEAS/arctic-data-training/events
This section readme should list all training events which link to a corresponding training/workshop folder. Each workshop folder readme should, in turn, provide overview of workshop, workshop agenda, and include links to appropriate content stored in arctic-data-training/materials.

Additionally, each workshop folder should include a license detailing appropriate terms for re-use.

**Comment by vlraymond** [comment]
comment from @mbjones 

> Regarding your proposal, we need to be sure to maintain the ability to create a website from the materials (currently at http://training.arcticdata.io/). Ideally that would integrate into our main ADC web site, but for now it is independent.   Also, we are slowly getting more sophisticated in our organization of materials as we do these training events across projects, with our recent SASAP training (https://nceas.github.io/sasap-training) providing the best example of how we want to organize training materials (https://nceas.github.io/sasap-training/materials/reproducible-analysis-in-r/).  We're still wrestling with the fact that lessons are re-used across many projects, with slight variations in the materials based on topic (e.g., arctic versus salmon) and the duration (e.g., ADC was 2 days, OSS was 3 weeks).  So, we need a holistic approach within projects, across projects, and integrated with the broader training community (such as the ESIP Data Management Training Clearinghouse).  

Let's discuss.

**Comment by jeanetteclark** [comment]
I think we can consider this complete
