### ISSUE TITLE
Update Github lesson to include `main`

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/arctic-data-training#38]
FYI @jeanetteclark after Oct 1 2020 all newly created github repositories will default to `main` not `master`. More info on their [repo](
https://github.com/github/renaming#:~:text=On%20October%201%2C%202020%2C%20any,this%20change%20at%20any%20time.)

**Comment by jeanetteclark** [comment]
Ah thanks for pointing that out! I'll update those sections.
