### ISSUE TITLE
Intern Feedback and Data Training Edits 11/9/2023

### ISSUE THREAD

**Issue by cjkra** [NCEAS/arctic-data-training#53]
The following edits were complied during four employees' progression through the data team training, as well as from previous interns' comments on the training:

https://docs.google.com/document/d/19hxWa9rRYFXrdeR38X3CApMTp4PiH7jsexKFoW6v_94/edit?usp=sharing

**Comment by jeanetteclark** [comment]
hey @cjkra I think this is the wrong repository, can you move this issue to https://github.com/NCEAS/datateam-training/issues
